version: '3.3'

services:
  gateway:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - '8080:80'
    depends_on:
      - web-api
      - web-app
  web-api:
    build: ./backend/
    restart: unless-stopped
    depends_on:
      - sql_db
  web-app:
    build: ./frontend/
    restart: unless-stopped
    depends_on:
      - web-api
  sql_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y